#!/bin/bash
#
# Remove database tables
#
echo "=> Removing database tables in $3"
mysql --user=$1 --password=$2 -BNe "show tables" $3 | tr '\n' ',' | sed -e 's/,$//' | awk '{print "SET FOREIGN_KEY_CHECKS = 0;DROP TABLE IF EXISTS " $1 ";SET FOREIGN_KEY_CHECKS = 1;"}' | mysql --user=$1 --password=$2 $3
echo "   Complete"
